package:
  name: dsge
  version: "0.0.4"

source:
  path: ..

requirements:

  build:
    - python {{ python }} 
    - setuptools
    - numpy
    - pandas
    - scipy
    - sympy
    - numba 

  run:
    - python
    - pandas
    - sympy
    - pyyaml
    - scipy
    - numba

test:
  # Python imports
  imports:
    - dsge

    # - dsge.extension
    # - dsge.fortran
    #- dsge.tests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: bsd
  #summary: Summary of the package

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
